---
containers: []
virtualmachines:
  - name: "buildhost"
    image: "rhel-10.1"
    memory: "16G"
    cores: 8
    image_size: "150G"
    packages:
      - podman
      - skopeo
      - buildah
      - libvirt
      - virt-install
      - qemu-kvm
      - libvirt-nss
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
    networks:
      - default
